title: Post Offices in Southern Europe
description: Interactive maps of post offices in Greece, Italy, Portugal, and Spain.
url: "https://andremarinha.github.io"
baseurl: "/postoffices_maps"

theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
